let cold_drink=()=>{
    let juice_data=[
    // soft drink.............0-18
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/45655a.jpg",
    name:"Red bull Energy drink",
    wt :"250 ml",
    price : "110",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/314a.jpg",
    name:"Thums up",
    wt :"750 ml",
    price : "38",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/15286a.jpg",
    name:"coca cola zero",
    wt :"300 ml",
    price : "38",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/402639a.jpg",
    name:"Budwiser",
    wt : "330 ml",
    price :"56",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/415875a.jpg",
    name:"Hoegarden",
    wt :"330 ml ",
    price : "75",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/18314a.jpg",
    name:"coca cola soft drink",
    wt : "500 ml",
    price : "88",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/300a.jpg",
    name:"mirinda soft drink",
    wt : "750 ml",
    price : "36",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/307a.jpg",
    name:"pepsi soft drink",
    wt : "750 ml",
    price :"36",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/456320a.jpg",
    name:"coolberg Ginger Non-alchoholic",
    wt : "330 ml",
    price : "68",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/456322a.jpg",
    name:"coolberg Malt Non-alchoholic",
    wt : "330 ml",
    price : "68",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/45655a.jpg",
    name:"Red bull Energy drink",
    wt :"250 ml",
    price : "110",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/314a.jpg",
    name:"Thums up",
    wt :"750 ml",
    price : "38",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/15286a.jpg",
    name:"coca cola zero",
    wt : "300 ml",
    price : "38",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/402639a.jpg",
    name:"Budwiser",
    wt : "330 ml",
    price :"56",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/415875a.jpg",
    name:"Hoegarden",
    wt : "330 ml ",
    price : "75",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/18314a.jpg",
    name:"coca cola soft drink",
    wt : "500 ml",
    price : "88",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/300a.jpg",
    name:"mirinda soft drink",
    wt :"750 ml",
    price : "36",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/307a.jpg",
    name:"pepsi soft drink",
    wt :"750 ml",
    price : "36",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/456320a.jpg",
    name:"coolberg Ginger Non-alchoholic",
    wt:"330 ml",
    price : "68",
},
{
    cat:"soft",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/456322a.jpg",
    name:"coolberg Malt Non-alchoholic",
    wt : "330 ml",
    price : "68",
},
// Fruit juice.....19-38
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/427007a.jpg",
    name:"Mazaa mango fruit drink",
    wt :"150 ml",
    price : "100",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/135928a.jpg",
    name:"B Natural Mixed Fruit",
    wt : "1 L",
    price :"88",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/376a.jpg",
    name:"Tropicana 100 % orange juice",
    wt :"weight",
    price :"price",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/62221a.jpg",
    name:"Real fruit powel apple",
    wt: "1L",
    price : "91",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/304a.jpg",
    name:"Paper Boat aam panna",
    wt : "250 ml",
    price : "24",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/394941a.jpg",
    name:"GHD coconut water",
    wt : "200 ml",
    price :"22",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/427007a.jpg",
    name:"Mazaa mango fruit drink",
    wt :"150 ml",
    price : "100",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/135928a.jpg",
    name:"B Natural Mixed Fruit",
    wt :"1 L",
    price : "88",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/376a.jpg",
    name:"Tropicana 100 % orange juice",
    wt :"weight",
    price : "price",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/62221a.jpg",
    name:"Real fruit powel apple",
    wt : "1L",
    price : "91",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/304a.jpg",
    name:"Paper Boat aam panna",
    wt : "250 ml",
    price : "24",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/394941a.jpg",
    name:"GHD coconut water",
    wt : "200 ml",
    price : "22",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/427007a.jpg",
    name:"Mazaa mango fruit drink",
    wt :"150 ml",
    price : "100",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/135928a.jpg",
    name:"B Natural Mixed Fruit",
    wt : "1 L",
    price : "88",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/376a.jpg",
    name:"Tropicana 100 % orange juice",
    wt : "weight",
    price : "price",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/62221a.jpg",
    name:"Real fruit powel apple",
    wt : "1L",
    price: "91",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/304a.jpg",
    name:"Paper Boat aam panna",
    wt : "250 ml",
    price : "24",
},
{
    cat:"juice",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/394941a.jpg",
    name:"GHD coconut water",
    wt : "200 ml",
    price : "22",
},
// soda &mixture.........39-49
{ 
    cat:"soda",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/316a.jpg",
    name:"Indian Tonic Water",
    wt :"300 ml",
    price : "50",
},
{
    cat:"soda",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/427620a.jpg",
    name:"Jimmy cocktail sex on the beach",
    wt :"250 ml",
    price : "88",
},
{
    cat:"soda",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/34354a.jpg",
    name:"Bisleri soda",
    wt : "750 ml",
    price : "14",
},
{
    cat:"soda",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/122997a.jpg",
    name:"Kinley club soda",
    wt : "weight",
    price : "price",
},
{
    cat:"soda",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/316a.jpg",
    name:"Indian Tonic Water",
    wt : "300 ml",
    price : "50",
},
{
    cat:"soda",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/427620a.jpg",
    name:"Jimmy cocktail sex on the beach",
    wt : "250 ml",
    price : "88",
},
{
    cat:"soda",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/34354a.jpg",
    name:"Bisleri soda",
    wt : "750 ml",
    price :"14",
},
{
    cat:"soda",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/122997a.jpg",
    name:"Kinley club soda",
    wt : "weight",
    price : "price",
},
// energy drink......50-60

{
    cat:"energyDrink",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/403174a.jpg",
    name:"Monster energy drink",
    wt:"350 ml",
    price : "100",
},
{
    cat:"energyDrink",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/3032a.jpg",
    name:"Gatorade orage flavour",
    wt :"500 ml",
    price : "50",
},
{
    cat:"energyDrink",
    image: "uhttps://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/377a.jpgrl",
    name:"Gatorade Blue Bolt",
    wt :"500 ml",
    price :"50",
},
{
    cat:"energyDrink",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/477354a.jpg",
    name:"ocean Natural Energy",
    wt : "250 ml",
    price : "70",
},
{
    cat:"energyDrink",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/374687a.jpg",
    name:"string Energy drink",
    wt :"250 ml",
    price :"20",
},
{
    cat:"energyDrink",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/403174a.jpg",
    name:"Monster energy drink",
    wt : "350 ml",
    price : "100",
},
{
    cat:"energyDrink",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/3032a.jpg",
    name:"Gatorade orage flavour",
    wt : "500 ml",
    price : "50",
},
{
    cat:"energyDrink",
    image: "uhttps://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/377a.jpgrl",
    name:"Gatorade Blue Bolt",
    wt : "500 ml",
    price : "50",
},
{
    cat:"energyDrink",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/477354a.jpg",
    name:"ocean Natural Energy",
    wt: "250 ml",
    price:"70",
},
{
    cat:"energyDrink",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/374687a.jpg",
    name:"string Energy drink",
    wt : "250 ml",
    price : "20",
},
// Herbal drink.....61-67
{
    cat:"herbalDrink",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/53703a.jpg",
    name:"Patanjali Aloe vera juice",
    wt : "1 L",
    price : "200",
},
{
    cat:"herbalDrink",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/10519a.jpg",
    name:"Patanjali Amla Juice",
    wt : "1 L",
    price: "130",
},
{
    cat:"herbalDrink",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/429705a.jpg",
    name:"Baidyanath Rich in vitamin c",
    wt : "250 ml",
    price : "70",
},
{
    cat:"herbalDrink",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/429705a.jpg",
    name:"Baidyanath Rich in vitamin c",
    wt : "250 ml",
    price : "80",
},
{
    cat:"herbalDrink",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/53703a.jpg",
    name:"Patanjali Aloe vera juice",
    wt : "1 L",
    price : "200",
},
{
    cat:"herbalDrink",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/10519a.jpg",
    name:"Patanjali Amla Juice",
    wt :"1 L",
    price : "130",
},
{
    cat:"herbalDrink",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/429705a.jpg",
    name:"Baidyanath Rich in vitamin c",
    wt :"1 l",
    price : "110",
},
// water..cubes..68-74
{
    cat:"water",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/319a.jpg",
    name:"Himalayan Natural Mineral Water",
    wt : "1 l",
    price : "63",
},
{
    
    cat:"water",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/280986a.jpg",
    name:"ocean crispy apple flavour",
    wt : "500 ml",
    price : "48",
},
{
    cat:"water",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/21699a.jpg",
    name:"Bisleri medica mineral water",
    wt : "1 l ",
    price : "39",
},
{
    cat:"water",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/246209a.jpg",
    name:"ocean pink Guava flavour",
    wt : "500 ml",
    price : "48",
},
{
    cat:"water",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/280986a.jpg",
    name:"ocean crispy apple flavour",
    wt :"500 ml",
    price : "48",
},
{
    cat:"water",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/21699a.jpg",
    name:"Bisleri medica mineral water",
    wt :"1 l ",
    price : "39",
},
{
    cat:"water",
    image: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=85,metadata=none,w=250,h=250/app/images/products/sliding_image/246209a.jpg",
    name:"ocean pink Guava flavour",
    wt :  "500 ml",
    price : "48",
},
  ]
return juice_data

}
// wt :
// price :
